# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Create SSL Certificate & key
      run: |
        mkdir -p ssl-certs
        openssl req -x509 -nodes -newkey rsa:2048 -keyout ssl-certs/key.key -out ssl-certs/cer.cer -days 3650 -subj "/C=US/ST=Utah/L=Lehi/O=AII/OU=IT/CN=localhost"
        sudo mkdir -p /usr/share/ca-certificates/extra
        sudo cp ssl-certs/cer.cer /usr/share/ca-certificates/extra/cer.cer
        sudo sh -c "echo "extra/cer.cer" >> /etc/ca-certificates.conf" 
        sudo update-ca-certificates 
    - name: Node.js tests
      run: npm i && npm run build --if-present && npm test
