# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Create SSL Certificate & key
      run: |
        mkdir -p ssl-certs
        openssl req -x509 -nodes -newkey rsa:2048 -keyout ssl-certs/key.key -out ssl-certs/cer.cer -days 3650 -subj "/C=US/ST=Utah/L=Lehi/O=AII/OU=IT/CN=localhost"
        sudo mkdir -p /usr/share/ca-certificates/extra
        sudo cp ssl-certs/cer.cer /usr/share/ca-certificates/extra/cer.cer
        sudo sh -c "echo "extra/cer.cer" >> /etc/ca-certificates.conf" 
        sudo update-ca-certificates
    - name: Write credentials files
      run: |
        mkdir -p aws-credentials
        sudo sh -c 'echo "$AWS_CREDENTIALS" >> aws-credentials/accessKeys.json'
        mkdir -p azure-credentials
        sudo sh -c 'echo "$AZURE_CONFIG_JS" >> azure-credentials/config.js'
        sudo sh -c 'echo "$AZURE_CONFIG_JSON" >> azure-credentials/config.json'
        mkdir -p db-credentials
        sudo sh -c 'echo "$DB_CONFIG_JS" >> db-credentials/config.js'
        sudo sh -c 'echo "$DB_CONFIG_JSON" >> db-credentials/config.json'
      env:
        AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
        AZURE_CONFIG_JS: ${{ secrets.AZURE_CONFIG_JS }}
        AZURE_CONFIG_JSON: ${{ secrets.AZURE_CONFIG_JSON }}
        DB_CONFIG_JS: ${{ secrets.DB_CONFIG_JS }}
        DB_CONFIG_JSON: ${{ secrets.DB_CONFIG_JSON }}
        

    - name: Node.js tests
      run: npm i && npm run build --if-present && npm test
